import "./globals.css";
import Navbar from "@/components/Navbar";
export const metadata = {
  title: "TrackmyLeet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#0a162b] text-white">
        
        {children}
      </body>
    </html>
  );
}
