import "./globals.css";
import Providers from "./providers";

export const metadata = {
  title: "TrackmyLeet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-[#0B1220] to-[#020617] min-h-screen">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
